# Generated by Django 5.1.15 on 2026-08-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spices', '0003_category_image_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
