# Generated by Django 5.1.15 on 2026-08-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spices', '0004_category_updated_at_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_package',
            field=models.ImageField(blank=True, help_text='Packaging view of the product', null=True, upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_side',
            field=models.ImageField(blank=True, help_text='Side view of the product', null=True, upload_to='posters/'),
        ),
    ]
