# Generated by Django 5.1.15 on 2026-08-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spices', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=50, help_text='Total available stock quantity (Admin editable)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=50, help_text='Available stock quantity for this variant (Admin editable)'),
        ),
    ]
