# Generated by Django 5.1.15 on 2026-08-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spices', '0009_product_stock_quantity_productvariant_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='reserved_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
