# Generated by Django 5.1.15 on 2026-08-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spices', '0010_cartitem_reserved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Courier / India Post Tracking Number provided by Admin', max_length=100, null=True),
        ),
    ]
