# Generated by Django 5.1.15 on 2026-08-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spices', '0011_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_path',
            field=models.CharField(blank=True, help_text='Supabase storage path e.g. payment-receipts/2026/08/pay_123.pdf', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_url',
            field=models.URLField(blank=True, help_text='Direct/Presigned Supabase URL to download PDF receipt', max_length=500, null=True),
        ),
    ]
