# Generated by Django 5.1.15 on 2026-08-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spices', '0013_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, help_text='Product health benefits (Admin editable)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Product ingredients list (Admin editable)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_info',
            field=models.TextField(blank=True, help_text='Storage & shelf life instructions (Admin editable)', null=True),
        ),
    ]
