# Generated by Django 5.1.15 on 2026-08-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spices', '0014_product_benefits_product_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='reserved_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
