# Generated by Django 5.1.15 on 2026-08-24 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spices', '0015_cartitem_reserved_at_auto_now_add'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, help_text='Unique non-sequential order reference e.g. LS-849201', max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='spices_orde_order_n_f0cad1_idx'),
        ),
    ]
