# Generated by Django 5.1.15 on 2026-09-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spices', '0016_order_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_notice',
            field=models.CharField(blank=True, default='Price may vary based on market price', help_text='Notice message shown on product card (e.g. Price may vary based on market price)', max_length=255, null=True),
        ),
    ]
